# -*- coding: utf-8 -*-
"""Impact of Feature Engineering on Machine Learning Model Performance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U4ZPAipUI-qY5jRHbrg2xT3lLnTuJOqt
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"
data = pd.read_csv(url, sep='\t', header=None, names=['label', 'message'])

data['label'] = data['label'].map({'ham': 0, 'spam': 1})

X_train, X_test, y_train, y_test = train_test_split(
    data['message'],
    data['label'],
    test_size=0.2,
    random_state=42
)

count_vectorizer = CountVectorizer(stop_words='english')

X_train_count = count_vectorizer.fit_transform(X_train)
X_test_count = count_vectorizer.transform(X_test)

lr_count = LogisticRegression()
lr_count.fit(X_train_count, y_train)

nb_count = MultinomialNB()
nb_count.fit(X_train_count, y_train)

lr_count_acc = accuracy_score(y_test, lr_count.predict(X_test_count))
nb_count_acc = accuracy_score(y_test, nb_count.predict(X_test_count))

tfidf_vectorizer = TfidfVectorizer(stop_words='english')

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

lr_tfidf = LogisticRegression()
lr_tfidf.fit(X_train_tfidf, y_train)

nb_tfidf = MultinomialNB()
nb_tfidf.fit(X_train_tfidf, y_train)

lr_tfidf_acc = accuracy_score(y_test, lr_tfidf.predict(X_test_tfidf))
nb_tfidf_acc = accuracy_score(y_test, nb_tfidf.predict(X_test_tfidf))

results = pd.DataFrame({
    "Model": ["LR + Count", "NB + Count", "LR + TFIDF", "NB + TFIDF"],
    "Accuracy": [lr_count_acc, nb_count_acc, lr_tfidf_acc, nb_tfidf_acc]
})

results

plt.bar(results["Model"], results["Accuracy"])
plt.xticks(rotation=45)
plt.title("Model Performance Comparison")
plt.ylabel("Accuracy")
plt.show()